# docker-compose.yml

version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - '5000:5000'
    networks:
      - app-network
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:80'
    networks:
      - app-network
    depends_on:
      - backend

  mongo:
    image: mongo:5
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
